name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    name: Build Docker Image and push to repositories
    runs-on: self-hosted

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Debug Docker Credentials
      run: |
        echo "DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}"
        echo "DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}"

    - name: Login to private Docker registry
      uses: docker/login-action@v2
      with:
        registry: http://192.168.3.247:5000
        username: hoyomi
        password: hoyomuwujak

    - name: Build and Push Docker Image
      run: |
        docker buildx create --use
        docker buildx build --platform linux/amd64,linux/arm64 -t 192.168.3.247:5000/network-image:latest .
        docker push 192.168.3.247:5000/network-image:latest
