name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    name: Build Docker Image and push to repositories
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Debug Docker Credentials
      run: |
        echo "DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}"
        echo "DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}"
      
    - name: Login to hub
      uses: docker/login-action@v2
      with:
        username: liqueddocker
        password: dckr_pat_vsc-Fv-7FB-n87uiwLkL0ZWmuZ8

    - name: Build and Push
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: liqueddocker/tpa-network-onsite:latest
